CREATE TABLE MARKET (
	MARK_ID		INTEGER NOT NULL UNIQUE, 
	MARK_NAME	TEXT NOT NULL, 
	PRIMARY KEY(MARK_ID AUTOINCREMENT)
); 

CREATE TABLE COMPANY (
	COMP_ID				INTEGER NOT NULL UNIQUE, 
	MARK_ID				INTEGER NOT NULL, 
	COMP_NAME			TEXT NOT NULL, 
	COMP_TICKER			CHAR(5) NOT NULL, 
	COMP_VOLUME			INTEGER NOT NULL DEFAULT 0, 
	COMP_SHARE_NUM		REAL NOT NULL DEFAULT 0, 
	COMP_CHNG_PRICE		REAL NOT NULL DEFAULT 0,
	COMP_CHNG_PRCNT		REAL NOT NULL DEFAULT 0,
	PRIMARY KEY(COMP_ID AUTOINCREMENT),
	FOREIGN KEY(MARK_ID) REFERENCES MARKET(MARK_ID)
); 

CREATE TABLE SHARE (
	SHARE_ID		INTEGER NOT NULL UNIQUE, 
	COMP_ID			INTEGER NOT NULL, 
	SHARE_PRICE		INTEGER NOT NULL DEFAULT 0, 
	PRIMARY KEY(SHARE_ID AUTOINCREMENT),
	FOREIGN KEY(COMP_ID) REFERENCES COMPANY(COMP_ID)
); 
